name: Keep Render App Awake

on:
  schedule:
    # This runs every 10 minutes, every day
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request
        run: curl -s https://cwc-b4ir.onrender.com > /dev/null
